import './global.scss';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout() {
  return <div>POCKET OFFER BACKEND</div>;
}
